In [1]:
import pandas as pd
#import matplotlib.pyplot as plt
import numpy as np

# Open file

In [2]:
loan_port=pd.read_csv("archive/loan_portfolio.csv")
loan_port

,loan_id,origination_date,maturity_date,maturity_months,sector,loan_type,collateral,initial_rating,credit_score,ead,...,pd_annual,lgd,el,unexpected_loss,rwa,defaulted,default_date,survival_months,recovery_rate,loss_given_default
0,L000001,2017-10-01,2019-10-01,24,Technology,mortgage,secured,B,704,1035611.99,...,0.041076,0.7858,33426.80,161508.03,442905.14,0,NaN,24,NaN,NaN
1,L000002,2016-06-01,2020-06-01,48,Healthcare,term_loan,unsecured,A,702,800786.92,...,0.000887,0.7034,499.82,16771.62,6622.66,0,NaN,48,NaN,NaN
2,L000003,2023-08-01,2024-12-31,36,Real_Estate,bond,secured,BBB,699,4327864.12,...,0.002622,0.5503,6243.54,121781.72,82726.94,0,NaN,36,NaN,NaN
3,L000004,2016-04-01,2024-12-31,120,Real_Estate,term_loan,secured,B,641,3810461.19,...,0.041679,0.3541,56237.33,269661.85,745144.64,0,NaN,120,NaN,NaN
4,L000005,2015-10-01,2019-10-01,48,Energy,bond,unsecured,CCC,597,2925538.53,...,0.136071,0.6576,261778.69,659614.05,3468567.58,0,NaN,48,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,L049996,2015-04-01,2024-12-31,120,Healthcare,term_loan,secured,B,663,348720.14,...,0.039657,0.5591,7731.88,38048.63,102447.40,0,NaN,120,NaN,NaN
49996,L049997,2023-07-01,2024-12-31,48,Technology,bond,secured,B,706,956642.42,...,0.040235,0.5406,20807.99,101627.30,275705.92,1,2025-11-01,28,0.4594,517160.89
49997,L049998,2016-01-01,2021-01-01,60,Telecom,lease,partially_secured,BB,698,9700964.56,...,0.010768,0.8027,83851.36,803689.31,1111030.55,0,NaN,60,NaN,NaN
49998,L049999,2016-04-01,2021-04-01,60,Utilities,mortgage,partially_secured,BB,696,4307501.86,...,0.010670,0.6887,31653.83,304797.56,419413.29,0,NaN,60,NaN,NaN
49999,L050000,2016-12-01,2020-12-01,48,Financials,term_loan,unsecured,B,689,2692736.33,...,0.039308,0.6246,66111.23,326834.30,875973.74,0,NaN,48,NaN,NaN

In [3]:
#loan_port[['loan_id','maturity_months','defaulted','survival_months']]
loan_port[(loan_port['maturity_months'] != loan_port['survival_months']) & (loan_port['defaulted']==1)][['maturity_months','defaulted','survival_months']]

       maturity_months  defaulted  survival_months
7                   48          1               16
9                   24          1               22
11                  48          1                1
19                  48          1               14
33                 120          1               13
...                ...        ...              ...
49967               48          1               14
49974               60          1               24
49980               60          1                8
49982              120          1                3
49996               48          1               28

[6830 rows x 3 columns]

In [4]:
loan_port.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 24 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   loan_id             50000 non-null  object
 1   origination_date    50000 non-null  object
 2   maturity_date       50000 non-null  object
 3   maturity_months     50000 non-null  int64
 4   sector              50000 non-null  object
 5   loan_type           50000 non-null  object
 6   collateral          50000 non-null  object
 7   initial_rating      50000 non-null  object
 8   credit_score        50000 non-null  int64
 9   ead                 50000 non-null  float64
 10  coupon_rate         50000 non-null  float64
 11  leverage            50000 non-null  float64
 12  interest_coverage   50000 non-null  float64
 13  debt_to_equity      50000 non-null  float64
 14  pd_annual           50000 non-null  float64
 15  lgd                 50000 non-null  float64
 16  el                  50000 non-null  float64
 17  unexpected_loss     50000 non-null  float64
 18  rwa                 50000 non-null  float64
 19  defaulted           50000 non-null  int64
 20  default_date        6950 non-null   object
 21  survival_months     50000 non-null  int64
 22  recovery_rate       6950 non-null   float64
 23  loss_given_default  6950 non-null   float64
dtypes: float64(12), int64(4), object(8)
memory usage: 9.2+ MB

In [5]:
type_col=['sector','loan_type','collateral','initial_rating']
for i in type_col:
    display(loan_port[i].value_counts())

sector
Energy         5132
Telecom        5077
Consumer       5043
Financials     5023
Industrials    5012
Healthcare     4982
Technology     4959
Utilities      4959
Retail         4951
Real_Estate    4862
Name: count, dtype: int64

loan_type
term_loan    17594
mortgage     12262
revolving    10158
bond          7458
lease         2528
Name: count, dtype: int64

collateral
secured              22657
unsecured            17398
partially_secured     9945
Name: count, dtype: int64

initial_rating
BBB    14001
BB     10918
A       7571
B       7559
CCC     4478
AA      3944
AAA     1529
Name: count, dtype: int64

In [6]:
loan_port.loc[0,'origination_date']

'2017-10-01'

# Train-Test Splitting

In [7]:
loan_port2=loan_port.copy()

datetime_col=[i for i in loan_port.keys() if 'date' in i]
# transform str to datetime
for i in datetime_col: 
    loan_port2[i]=pd.to_datetime(loan_port2[i])

loan_port2

,loan_id,origination_date,maturity_date,maturity_months,sector,loan_type,collateral,initial_rating,credit_score,ead,...,pd_annual,lgd,el,unexpected_loss,rwa,defaulted,default_date,survival_months,recovery_rate,loss_given_default
0,L000001,2017-10-01,2019-10-01,24,Technology,mortgage,secured,B,704,1035611.99,...,0.041076,0.7858,33426.80,161508.03,442905.14,0,NaT,24,NaN,NaN
1,L000002,2016-06-01,2020-06-01,48,Healthcare,term_loan,unsecured,A,702,800786.92,...,0.000887,0.7034,499.82,16771.62,6622.66,0,NaT,48,NaN,NaN
2,L000003,2023-08-01,2024-12-31,36,Real_Estate,bond,secured,BBB,699,4327864.12,...,0.002622,0.5503,6243.54,121781.72,82726.94,0,NaT,36,NaN,NaN
3,L000004,2016-04-01,2024-12-31,120,Real_Estate,term_loan,secured,B,641,3810461.19,...,0.041679,0.3541,56237.33,269661.85,745144.64,0,NaT,120,NaN,NaN
4,L000005,2015-10-01,2019-10-01,48,Energy,bond,unsecured,CCC,597,2925538.53,...,0.136071,0.6576,261778.69,659614.05,3468567.58,0,NaT,48,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,L049996,2015-04-01,2024-12-31,120,Healthcare,term_loan,secured,B,663,348720.14,...,0.039657,0.5591,7731.88,38048.63,102447.40,0,NaT,120,NaN,NaN
49996,L049997,2023-07-01,2024-12-31,48,Technology,bond,secured,B,706,956642.42,...,0.040235,0.5406,20807.99,101627.30,275705.92,1,2025-11-01,28,0.4594,517160.89
49997,L049998,2016-01-01,2021-01-01,60,Telecom,lease,partially_secured,BB,698,9700964.56,...,0.010768,0.8027,83851.36,803689.31,1111030.55,0,NaT,60,NaN,NaN
49998,L049999,2016-04-01,2021-04-01,60,Utilities,mortgage,partially_secured,BB,696,4307501.86,...,0.010670,0.6887,31653.83,304797.56,419413.29,0,NaT,60,NaN,NaN
49999,L050000,2016-12-01,2020-12-01,48,Financials,term_loan,unsecured,B,689,2692736.33,...,0.039308,0.6246,66111.23,326834.30,875973.74,0,NaT,48,NaN,NaN

In [8]:
loan_port2.sort_values(['origination_date','maturity_date'], inplace=True)
loan_port2.reset_index(drop=True, inplace=True)

In [9]:
split_point=int(len(loan_port2)*0.7)

train_data=loan_port2[:split_point].copy()
test_data=loan_port2[split_point:].copy()

In [10]:
train_stat=train_data.describe()
display(train_stat)

,origination_date,maturity_date,maturity_months,credit_score,ead,coupon_rate,leverage,interest_coverage,debt_to_equity,pd_annual,lgd,el,unexpected_loss,rwa,defaulted,default_date,survival_months,recovery_rate,loss_given_default
count,35000,35000,35000.000000,35000.000000,3.500000e+04,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,35000.000000,3.500000e+04,3.500000e+04,3.500000e+04,35000.000000,5753,35000.000000,5753.000000,5.753000e+03
mean,2018-02-06 08:17:54.651428608,2022-03-26 11:27:34.765714176,54.014743,715.089686,3.308804e+06,2.931451,6.904236,3.763323,2.086235,0.022912,0.546819,4.007181e+04,1.850387e+05,5.309515e+05,0.164371,2020-06-15 02:17:10.001738240,48.303371,0.455569,1.753435e+06
min,2015-01-01 00:00:00,2016-01-01 00:00:00,12.000000,518.000000,5.000000e+04,1.000000,0.500000,0.500000,0.100000,0.000158,0.091800,3.600000e+00,2.735300e+02,4.765000e+01,0.000000,2015-02-01 00:00:00,1.000000,0.020000,1.433000e+04
25%,2016-07-01 00:00:00,2020-07-01 00:00:00,36.000000,679.000000,5.504071e+05,2.483000,4.050000,2.370000,1.030000,0.001295,0.443400,7.984225e+02,1.739675e+04,1.057908e+04,0.000000,2020-04-01 00:00:00,35.000000,0.353700,2.899526e+05
50%,2018-02-01 00:00:00,2022-06-01 00:00:00,48.000000,715.000000,1.396801e+06,3.010000,6.080000,3.310000,1.650000,0.002806,0.544900,3.631560e+03,5.260387e+04,4.811816e+04,0.000000,2020-05-01 00:00:00,48.000000,0.455700,7.219356e+05
75%,2019-09-01 00:00:00,2024-05-01 00:00:00,60.000000,750.000000,3.424126e+06,3.458000,9.050000,4.650000,2.630000,0.016640,0.647400,1.893992e+04,1.579063e+05,2.509540e+05,0.000000,2020-06-01 00:00:00,60.000000,0.561500,1.766335e+06
max,2021-04-01 00:00:00,2024-12-31 00:00:00,120.000000,850.000000,3.611778e+08,5.896000,15.000000,20.000000,10.000000,0.242523,0.980000,6.411410e+06,2.239212e+07,8.495118e+07,1.000000,2030-12-01 00:00:00,120.000000,0.854500,1.113264e+08
std,NaN,NaN,26.719180,50.841787,6.723379e+06,0.819725,3.683419,2.009622,1.564232,0.041357,0.144888,1.686148e+05,5.162670e+05,2.234146e+06,0.370618,NaN,26.877033,0.145196,3.807581e+06

In [11]:
# prepare for forward transform

month_col=[i for i in loan_port2.keys() if 'month' in i]
dummy_col=['sector','loan_type','collateral']
z_scale_col=['ead', 'coupon_rate', 'leverage', 'interest_coverage', 'debt_to_equity', 'pd_annual', 'lgd', 'el', 'unexpected_loss', 'rwa', 'recovery_rate', 'loss_given_default']
#'pd_annual', 'lgd' and 'recovery_rate' already in interval 0-1. 'defaulted' is boolean

# re-scale initial rating
def rate_to_num(rate_char):
    if rate_char=='AAA': return 7/7
    elif  rate_char=='AA': return 6/7
    elif  rate_char=='A': return 5/7
    elif  rate_char=='BBB': return 4/7
    elif  rate_char=='BB': return 3/7
    elif  rate_char=='B': return 2/7
    elif  rate_char=='CCC': return 1/7
    else: return 0

# transform initial rating as number 0-1 to string
def num_to_rate(num):
    temp=np.round(num*7)
    if temp==7: return'AAA'
    elif temp==6: return 'AA'
    elif temp==5: return 'A'
    elif temp==4: return 'BBB'
    elif temp==3: return 'BB'
    elif temp==2: return 'B'
    elif temp==1: return 'CCC'
    else: return 'D'

In [12]:
display(month_col)
display(datetime_col)

['maturity_months', 'survival_months']

['origination_date', 'maturity_date', 'default_date']

In [13]:
def forward_transform(loan_data):
    loan_port2=loan_data.copy()

    # re-scale month to 0-1
    for i in month_col: 
        loan_port2[i]=(loan_port2[i]-12)/(120-12)

    # re-scale initial rating to 0-1
    loan_port2['initial_rating']=loan_port2['initial_rating'].apply(rate_to_num) 

    # re-scale credit score to 0-1
    loan_port2['credit_score']=(loan_port2['credit_score']-300)/(850-300)
    
    # make one-hot encoder
    dummy_get=[pd.get_dummies(loan_port2[i]).astype('int') for i in dummy_col]
    dummy_col2=sum([list(dummy_get[i].keys()) for i in range(len(dummy_col))],[])
    for i in range(len(dummy_col)):
        loan_port2=pd.merge(loan_port2, dummy_get[i], left_index=True, right_index=True)

    # transform to z-score
    for i in z_scale_col:
        loan_port2[i]=(loan_port2[i]-train_stat.loc['mean',i])/train_stat.loc['std',i]

    return loan_port2

In [14]:
train_data2=forward_transform(train_data)
train_data2

,loan_id,origination_date,maturity_date,maturity_months,sector,loan_type,collateral,initial_rating,credit_score,ead,...,Telecom,Utilities,bond,lease,mortgage,revolving,term_loan,partially_secured,secured,unsecured
0,L008633,2015-01-01,2016-01-01,0.000000,Consumer,term_loan,unsecured,0.714286,0.700000,-0.289402,...,0,0,0,0,0,0,1,0,0,1
1,L009184,2015-01-01,2016-01-01,0.000000,Industrials,bond,unsecured,1.000000,0.805455,-0.377311,...,0,0,1,0,0,0,0,0,0,1
2,L010332,2015-01-01,2016-01-01,0.000000,Retail,lease,secured,0.714286,0.794545,0.814112,...,0,0,0,1,0,0,0,0,1,0
3,L011575,2015-01-01,2016-01-01,0.000000,Real_Estate,revolving,partially_secured,0.571429,0.934545,-0.091036,...,0,0,0,0,0,1,0,1,0,0
4,L014402,2015-01-01,2016-01-01,0.000000,Energy,bond,partially_secured,0.571429,0.838182,-0.063589,...,0,0,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34995,L015462,2021-04-01,2024-12-31,0.444444,Consumer,mortgage,secured,0.571429,0.674545,-0.464890,...,0,0,0,0,1,0,0,0,1,0
34996,L015508,2021-04-01,2024-12-31,0.333333,Utilities,mortgage,unsecured,0.428571,0.821818,-0.155166,...,0,1,0,0,1,0,0,0,0,1
34997,L015595,2021-04-01,2024-12-31,1.000000,Technology,revolving,unsecured,0.571429,0.803636,-0.238896,...,0,0,0,0,0,1,0,0,0,1
34998,L015659,2021-04-01,2024-12-31,0.666667,Real_Estate,term_loan,secured,0.857143,0.838182,-0.228936,...,0,0,0,0,0,0,1,0,1,0
34999,L015706,2021-04-01,2024-12-31,0.444444,Telecom,mortgage,unsecured,0.857143,0.821818,-0.439934,...,1,0,0,0,1,0,0,0,0,1

In [15]:
print(', '.join(dummy_col)+'\n')
sector_col=list(loan_port['sector'].value_counts().keys())
print(', '.join(sector_col))
loan_type_col=list(loan_port['loan_type'].value_counts().keys())
print(', '.join(loan_type_col))
collateral_col=list(loan_port['collateral'].value_counts().keys())
print(', '.join(collateral_col))

dummy_backward=[sector_col, loan_type_col, collateral_col]

sector, loan_type, collateral

Energy, Telecom, Consumer, Financials, Industrials, Healthcare, Technology, Utilities, Retail, Real_Estate
term_loan, mortgage, revolving, bond, lease
secured, unsecured, partially_secured

In [16]:
def backward_transform(loan_data):
    loan_port2=loan_data.copy()

    # re-scale month
    for i in month_col: 
        loan_port2[i]=(loan_port2[i]*(120-12)+12).astype('int')

    # re-scale initial rating to 0-1
    loan_port2['initial_rating']=loan_port2['initial_rating'].apply(num_to_rate) 

    # re-scale credit score
    loan_port2['credit_score']=(loan_port2['credit_score']*(850-300)+300).astype('int')
    
    # transform one-hot encoder into columns
    dummy_backward2=[pd.from_dummies(loan_port2[dummy_backward[i]]).rename(columns={'':dummy_col[i]}) for i in range(len(dummy_col)) ]
    for i in range(len(dummy_col)):
        loan_port2=pd.merge(loan_port2, dummy_backward2[i], left_index=True, right_index=True, suffixes=(None,'_f'))

    # transform to z-score
    for i in z_scale_col:
        loan_port2[i]=loan_port2[i]*train_stat.loc['std',i]+train_stat.loc['mean',i]

    return loan_port2

In [17]:
train_data3=backward_transform(train_data2)
train_data3

,loan_id,origination_date,maturity_date,maturity_months,sector,loan_type,collateral,initial_rating,credit_score,ead,...,lease,mortgage,revolving,term_loan,partially_secured,secured,unsecured,sector_f,loan_type_f,collateral_f
0,L008633,2015-01-01,2016-01-01,12,Consumer,term_loan,unsecured,A,685,1363047.68,...,0,0,0,1,0,0,1,Consumer,term_loan,unsecured
1,L009184,2015-01-01,2016-01-01,12,Industrials,bond,unsecured,AAA,743,771996.30,...,0,0,0,0,0,0,1,Industrials,bond,unsecured
2,L010332,2015-01-01,2016-01-01,12,Retail,lease,secured,A,737,8782386.79,...,1,0,0,0,0,1,0,Retail,lease,secured
3,L011575,2015-01-01,2016-01-01,12,Real_Estate,revolving,partially_secured,BBB,814,2696736.27,...,0,0,1,0,1,0,0,Real_Estate,revolving,partially_secured
4,L014402,2015-01-01,2016-01-01,12,Energy,bond,partially_secured,BBB,761,2881272.51,...,0,0,0,0,1,0,0,Energy,bond,partially_secured
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34995,L015462,2021-04-01,2024-12-31,60,Consumer,mortgage,secured,BBB,671,183173.98,...,0,1,0,0,0,1,0,Consumer,mortgage,secured
34996,L015508,2021-04-01,2024-12-31,48,Utilities,mortgage,unsecured,BB,752,2265567.38,...,0,1,0,0,0,0,1,Utilities,mortgage,unsecured
34997,L015595,2021-04-01,2024-12-31,120,Technology,revolving,unsecured,BBB,742,1702614.68,...,0,0,1,0,0,0,1,Technology,revolving,unsecured
34998,L015659,2021-04-01,2024-12-31,84,Real_Estate,term_loan,secured,AA,761,1769578.35,...,0,0,0,1,0,1,0,Real_Estate,term_loan,secured
34999,L015706,2021-04-01,2024-12-31,60,Telecom,mortgage,unsecured,AA,752,350961.51,...,0,1,0,0,0,0,1,Telecom,mortgage,unsecured

In [18]:
loan_port2[:split_point]

,loan_id,origination_date,maturity_date,maturity_months,sector,loan_type,collateral,initial_rating,credit_score,ead,...,pd_annual,lgd,el,unexpected_loss,rwa,defaulted,default_date,survival_months,recovery_rate,loss_given_default
0,L008633,2015-01-01,2016-01-01,12,Consumer,term_loan,unsecured,A,685,1363047.68,...,0.000912,0.6997,870.12,28794.11,11529.13,0,NaT,12,NaN,NaN
1,L009184,2015-01-01,2016-01-01,12,Industrials,bond,unsecured,AAA,743,771996.30,...,0.000179,0.6062,83.59,6253.76,1107.50,0,NaT,12,NaN,NaN
2,L010332,2015-01-01,2016-01-01,12,Retail,lease,secured,A,737,8782386.79,...,0.000879,0.5106,3941.65,132890.75,52226.86,0,NaT,12,NaN,NaN
3,L011575,2015-01-01,2016-01-01,12,Real_Estate,revolving,partially_secured,BBB,814,2696736.27,...,0.002542,0.3529,2419.19,47921.19,32054.31,0,NaT,12,NaN,NaN
4,L014402,2015-01-01,2016-01-01,12,Energy,bond,partially_secured,BBB,761,2881272.51,...,0.002641,0.4669,3552.37,69038.10,47068.86,0,NaT,12,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34995,L015462,2021-04-01,2024-12-31,60,Consumer,mortgage,secured,BBB,671,183173.98,...,0.002648,0.5752,279.01,5414.70,3696.86,0,NaT,60,NaN,NaN
34996,L015508,2021-04-01,2024-12-31,48,Utilities,mortgage,unsecured,BB,752,2265567.38,...,0.010180,0.4544,10479.97,103339.35,138859.55,0,NaT,48,NaN,NaN
34997,L015595,2021-04-01,2024-12-31,120,Technology,revolving,unsecured,BBB,742,1702614.68,...,0.002530,0.5843,2516.85,49975.21,33348.25,0,NaT,120,NaN,NaN
34998,L015659,2021-04-01,2024-12-31,84,Real_Estate,term_loan,secured,AA,761,1769578.35,...,0.000423,0.1935,144.90,7042.45,1919.98,0,NaT,84,NaN,NaN
34999,L015706,2021-04-01,2024-12-31,60,Telecom,mortgage,unsecured,AA,752,350961.51,...,0.000421,0.6917,102.14,4978.42,1353.33,0,NaT,60,NaN,NaN

In [19]:
#catagorize feature column
input_col=['maturity_months','initial_rating','credit_score','ead','coupon_rate','leverage','interest_coverate','debt_to_equity']+sum(dummy_backward,[])  #dummy_col
cal_input_col=['pd_annual','lgd','el','unexpected_loss','rwa']
output_col=['defaulted','survival_months']
cal_output_col=['recovery_rate','loss_given_default']

In [20]:
sum(dummy_backward,[])

['Energy',
 'Telecom',
 'Consumer',
 'Financials',
 'Industrials',
 'Healthcare',
 'Technology',
 'Utilities',
 'Retail',
 'Real_Estate',
 'term_loan',
 'mortgage',
 'revolving',
 'bond',
 'lease',
 'secured',
 'unsecured',
 'partially_secured']

In [21]:
test_data2=forward_transform(test_data)
test_data2

,loan_id,origination_date,maturity_date,maturity_months,sector,loan_type,collateral,initial_rating,credit_score,ead,...,Telecom,Utilities,bond,lease,mortgage,revolving,term_loan,partially_secured,secured,unsecured
35000,L016040,2021-04-01,2024-12-31,0.333333,Energy,bond,partially_secured,0.142857,0.687273,-0.426455,...,0,0,1,0,0,0,0,1,0,0
35001,L016223,2021-04-01,2024-12-31,0.444444,Financials,revolving,partially_secured,0.285714,0.807273,-0.349716,...,0,0,0,0,0,1,0,1,0,0
35002,L016308,2021-04-01,2024-12-31,1.000000,Retail,term_loan,unsecured,0.428571,0.647273,0.079292,...,0,0,0,0,0,0,1,0,0,1
35003,L016659,2021-04-01,2024-12-31,0.444444,Industrials,mortgage,secured,0.285714,0.601818,-0.382590,...,0,0,0,0,1,0,0,0,1,0
35004,L016683,2021-04-01,2024-12-31,1.000000,Real_Estate,term_loan,unsecured,0.428571,0.707273,1.054665,...,0,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,L049222,2023-12-01,2024-12-31,0.666667,Financials,mortgage,partially_secured,0.571429,0.740000,-0.435100,...,0,0,0,0,1,0,0,1,0,0
49996,L049376,2023-12-01,2024-12-31,1.000000,Telecom,mortgage,secured,0.571429,0.763636,-0.385395,...,1,0,0,0,1,0,0,0,1,0
49997,L049468,2023-12-01,2024-12-31,0.666667,Energy,term_loan,unsecured,0.428571,0.758182,-0.064488,...,0,0,0,0,0,0,1,0,0,1
49998,L049469,2023-12-01,2024-12-31,1.000000,Retail,lease,secured,0.857143,0.910909,-0.259069,...,0,0,0,1,0,0,0,0,1,0
49999,L049964,2023-12-01,2024-12-31,0.666667,Healthcare,mortgage,secured,0.857143,0.865455,-0.322409,...,0,0,0,0,1,0,0,0,1,0

# Save

In [22]:
train_data2.to_csv('train_data.csv', index=False)
test_data2.to_csv('test_data.csv', index=False)
train_stat.to_csv('train_stat.csv', index=False)